#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ ! -f "$basedir/../ts-patch/bin/persist.js" ]; then
  rm -rf "$basedir/postinstall"
  rm -rf "$basedir/postinstall.cmd"
  exit 0
fi

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../ts-patch/bin/persist.js"
  ret=$?
else
  node  "$basedir/../ts-patch/bin/persist.js"
  ret=$?
fi
exit $ret
