#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

[ ! -f "$basedir/../ts-patch/bin/persist.js" ] && rm -rf "$basedir/persist*"

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../ts-patch/bin/persist.js"
  ret=$?
else
  node  "$basedir/../ts-patch/bin/persist.js"
  ret=$?
fi
exit $ret
